import { addIcons } from 'ionicons';
import {
  alertCircleOutline,
  arrowBack,
  arrowForward,
  barChartOutline,
  checkmark,
  checkmarkCircleOutline,
  chevronForward,
  closeCircleOutline,
  closeOutline,
  cloudDownloadOutline,
  cloudOfflineOutline,
  eyeOffOutline,
  eyeOutline,
  heart,
  heartOutline,
  homeOutline,
  informationCircleOutline,
  leafOutline,
  lockClosedOutline,
  logOutOutline,
  mailOutline,
  optionsOutline,
  personOutline,
  pricetagOutline,
  pulseOutline,
  refreshOutline,
  searchOutline,
  serverOutline,
  shieldCheckmarkOutline,
  sparklesOutline,
  storefrontOutline,
  swapHorizontalOutline,
  thumbsDownOutline,
  trashOutline,
  trophyOutline,
} from 'ionicons/icons';

/** Registro explícito de íconos (Ionic standalone): solo se empaquetan los usados. */
export function registerIcons(): void {
  addIcons({
    'alert-circle-outline': alertCircleOutline,
    'arrow-back': arrowBack,
    'arrow-forward': arrowForward,
    'bar-chart-outline': barChartOutline,
    checkmark,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'chevron-forward': chevronForward,
    'close-circle-outline': closeCircleOutline,
    'close-outline': closeOutline,
    'cloud-download-outline': cloudDownloadOutline,
    'cloud-offline-outline': cloudOfflineOutline,
    'eye-off-outline': eyeOffOutline,
    'eye-outline': eyeOutline,
    heart,
    'heart-outline': heartOutline,
    'home-outline': homeOutline,
    'information-circle-outline': informationCircleOutline,
    'leaf-outline': leafOutline,
    'lock-closed-outline': lockClosedOutline,
    'log-out-outline': logOutOutline,
    'mail-outline': mailOutline,
    'options-outline': optionsOutline,
    'person-outline': personOutline,
    'pricetag-outline': pricetagOutline,
    'pulse-outline': pulseOutline,
    'refresh-outline': refreshOutline,
    'search-outline': searchOutline,
    'server-outline': serverOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'sparkles-outline': sparklesOutline,
    'storefront-outline': storefrontOutline,
    'swap-horizontal-outline': swapHorizontalOutline,
    'thumbs-down-outline': thumbsDownOutline,
    'trash-outline': trashOutline,
    'trophy-outline': trophyOutline,
  });
}
